//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:00 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.tokenrestrictiontemplate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.as.ams.contentkeyauthorizationpolicyoptions.tokenrestrictiontemplate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArrayOfTokenClaim_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "ArrayOfTokenClaim");
    private final static QName _TokenClaim_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "TokenClaim");
    private final static QName _TokenRestrictionTemplate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "TokenRestrictionTemplate");
    private final static QName _TokenVerificationKey_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "TokenVerificationKey");
    private final static QName _SymmetricVerificationKey_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "SymmetricVerificationKey");
    private final static QName _ArrayOfTokenVerificationKey_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "ArrayOfTokenVerificationKey");
    private final static QName _TokenRestrictionTemplateAlternateVerificationKeys_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "AlternateVerificationKeys");
    private final static QName _TokenRestrictionTemplateRequiredClaims_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "RequiredClaims");
    private final static QName _TokenClaimClaimValue_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", "ClaimValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.as.ams.contentkeyauthorizationpolicyoptions.tokenrestrictiontemplate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SymmetricVerificationKey }
     * 
     */
    public SymmetricVerificationKey createSymmetricVerificationKey() {
        return new SymmetricVerificationKey();
    }

    /**
     * Create an instance of {@link TokenClaim }
     * 
     */
    public TokenClaim createTokenClaim() {
        return new TokenClaim();
    }

    /**
     * Create an instance of {@link TokenRestrictionTemplate }
     * 
     */
    public TokenRestrictionTemplate createTokenRestrictionTemplate() {
        return new TokenRestrictionTemplate();
    }

    /**
     * Create an instance of {@link TokenVerificationKey }
     * 
     */
    public TokenVerificationKey createTokenVerificationKey() {
        return new TokenVerificationKey();
    }

    /**
     * Create an instance of {@link ArrayOfTokenClaim }
     * 
     */
    public ArrayOfTokenClaim createArrayOfTokenClaim() {
        return new ArrayOfTokenClaim();
    }

    /**
     * Create an instance of {@link ArrayOfTokenVerificationKey }
     * 
     */
    public ArrayOfTokenVerificationKey createArrayOfTokenVerificationKey() {
        return new ArrayOfTokenVerificationKey();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTokenClaim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "ArrayOfTokenClaim")
    public JAXBElement<ArrayOfTokenClaim> createArrayOfTokenClaim(ArrayOfTokenClaim value) {
        return new JAXBElement<ArrayOfTokenClaim>(_ArrayOfTokenClaim_QNAME, ArrayOfTokenClaim.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokenClaim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "TokenClaim")
    public JAXBElement<TokenClaim> createTokenClaim(TokenClaim value) {
        return new JAXBElement<TokenClaim>(_TokenClaim_QNAME, TokenClaim.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokenRestrictionTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "TokenRestrictionTemplate")
    public JAXBElement<TokenRestrictionTemplate> createTokenRestrictionTemplate(TokenRestrictionTemplate value) {
        return new JAXBElement<TokenRestrictionTemplate>(_TokenRestrictionTemplate_QNAME, TokenRestrictionTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokenVerificationKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "TokenVerificationKey")
    public JAXBElement<TokenVerificationKey> createTokenVerificationKey(TokenVerificationKey value) {
        return new JAXBElement<TokenVerificationKey>(_TokenVerificationKey_QNAME, TokenVerificationKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymmetricVerificationKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "SymmetricVerificationKey")
    public JAXBElement<SymmetricVerificationKey> createSymmetricVerificationKey(SymmetricVerificationKey value) {
        return new JAXBElement<SymmetricVerificationKey>(_SymmetricVerificationKey_QNAME, SymmetricVerificationKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTokenVerificationKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "ArrayOfTokenVerificationKey")
    public JAXBElement<ArrayOfTokenVerificationKey> createArrayOfTokenVerificationKey(ArrayOfTokenVerificationKey value) {
        return new JAXBElement<ArrayOfTokenVerificationKey>(_ArrayOfTokenVerificationKey_QNAME, ArrayOfTokenVerificationKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTokenVerificationKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "AlternateVerificationKeys", scope = TokenRestrictionTemplate.class)
    public JAXBElement<ArrayOfTokenVerificationKey> createTokenRestrictionTemplateAlternateVerificationKeys(ArrayOfTokenVerificationKey value) {
        return new JAXBElement<ArrayOfTokenVerificationKey>(_TokenRestrictionTemplateAlternateVerificationKeys_QNAME, ArrayOfTokenVerificationKey.class, TokenRestrictionTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTokenClaim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "RequiredClaims", scope = TokenRestrictionTemplate.class)
    public JAXBElement<ArrayOfTokenClaim> createTokenRestrictionTemplateRequiredClaims(ArrayOfTokenClaim value) {
        return new JAXBElement<ArrayOfTokenClaim>(_TokenRestrictionTemplateRequiredClaims_QNAME, ArrayOfTokenClaim.class, TokenRestrictionTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", name = "ClaimValue", scope = TokenClaim.class)
    public JAXBElement<String> createTokenClaimClaimValue(String value) {
        return new JAXBElement<String>(_TokenClaimClaimValue_QNAME, String.class, TokenClaim.class, value);
    }

}
