//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:00 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.tokenrestrictiontemplate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenRestrictionTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TokenRestrictionTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlternateVerificationKeys" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1}ArrayOfTokenVerificationKey" minOccurs="0"/>
 *         &lt;element name="Audience" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Issuer" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="PrimaryVerificationKey" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1}TokenVerificationKey"/>
 *         &lt;element name="RequiredClaims" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1}ArrayOfTokenClaim" minOccurs="0"/>
 *         &lt;element name="TokenType" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1}TokenType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenRestrictionTemplate", propOrder = {
    "alternateVerificationKeys",
    "audience",
    "issuer",
    "primaryVerificationKey",
    "requiredClaims",
    "tokenType"
})
public class TokenRestrictionTemplate {

    @XmlElementRef(name = "AlternateVerificationKeys", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfTokenVerificationKey> alternateVerificationKeys;
    @XmlElement(name = "Audience", required = true, nillable = true)
    @XmlSchemaType(name = "anyURI")
    protected String audience;
    @XmlElement(name = "Issuer", required = true, nillable = true)
    @XmlSchemaType(name = "anyURI")
    protected String issuer;
    @XmlElement(name = "PrimaryVerificationKey", required = true, nillable = true)
    protected TokenVerificationKey primaryVerificationKey;
    @XmlElementRef(name = "RequiredClaims", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/TokenRestrictionTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfTokenClaim> requiredClaims;
    @XmlElement(name = "TokenType", required = true)
    @XmlSchemaType(name = "string")
    protected TokenType tokenType;

    /**
     * Gets the value of the alternateVerificationKeys property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfTokenVerificationKey }{@code >}
     *     
     */
    public JAXBElement<ArrayOfTokenVerificationKey> getAlternateVerificationKeys() {
        return alternateVerificationKeys;
    }

    /**
     * Sets the value of the alternateVerificationKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfTokenVerificationKey }{@code >}
     *     
     */
    public void setAlternateVerificationKeys(JAXBElement<ArrayOfTokenVerificationKey> value) {
        this.alternateVerificationKeys = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the primaryVerificationKey property.
     * 
     * @return
     *     possible object is
     *     {@link TokenVerificationKey }
     *     
     */
    public TokenVerificationKey getPrimaryVerificationKey() {
        return primaryVerificationKey;
    }

    /**
     * Sets the value of the primaryVerificationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenVerificationKey }
     *     
     */
    public void setPrimaryVerificationKey(TokenVerificationKey value) {
        this.primaryVerificationKey = value;
    }

    /**
     * Gets the value of the requiredClaims property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfTokenClaim }{@code >}
     *     
     */
    public JAXBElement<ArrayOfTokenClaim> getRequiredClaims() {
        return requiredClaims;
    }

    /**
     * Sets the value of the requiredClaims property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfTokenClaim }{@code >}
     *     
     */
    public void setRequiredClaims(JAXBElement<ArrayOfTokenClaim> value) {
        this.requiredClaims = value;
    }

    /**
     * Gets the value of the tokenType property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType }
     *     
     */
    public TokenType getTokenType() {
        return tokenType;
    }

    /**
     * Sets the value of the tokenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType }
     *     
     */
    public void setTokenType(TokenType value) {
        this.tokenType = value;
    }

}
