//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentEncryptionKeyFromHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentEncryptionKeyFromHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}PlayReadyContentKey">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentEncryptionKeyFromHeader")
public class ContentEncryptionKeyFromHeader
    extends PlayReadyContentKey
{


}
