//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExplicitAnalogTelevisionRestriction_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ExplicitAnalogTelevisionRestriction");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _AgcAndColorStripeRestriction_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "AgcAndColorStripeRestriction");
    private final static QName _PlayReadyContentKey_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayReadyContentKey");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _ContentEncryptionKeyFromHeader_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ContentEncryptionKeyFromHeader");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _PlayReadyLicenseType_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayReadyLicenseType");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _PlayReadyLicenseTemplate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayReadyLicenseTemplate");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _ContentEncryptionKeyFromKeyIdentifier_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ContentEncryptionKeyFromKeyIdentifier");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _ScmsRestriction_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ScmsRestriction");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _UnknownOutputPassingOption_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "UnknownOutputPassingOption");
    private final static QName _ContentType_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ContentType");
    private final static QName _PlayReadyPlayRight_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayReadyPlayRight");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _PlayReadyLicenseResponseTemplate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayReadyLicenseResponseTemplate");
    private final static QName _ArrayOfPlayReadyLicenseTemplate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ArrayOfPlayReadyLicenseTemplate");
    private final static QName _PlayReadyPlayRightUncompressedDigitalVideoOpl_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "UncompressedDigitalVideoOpl");
    private final static QName _PlayReadyPlayRightUncompressedDigitalAudioOpl_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "UncompressedDigitalAudioOpl");
    private final static QName _PlayReadyPlayRightCompressedDigitalAudioOpl_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "CompressedDigitalAudioOpl");
    private final static QName _PlayReadyPlayRightCompressedDigitalVideoOpl_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "CompressedDigitalVideoOpl");
    private final static QName _PlayReadyPlayRightFirstPlayExpiration_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "FirstPlayExpiration");
    private final static QName _PlayReadyPlayRightAnalogVideoOpl_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "AnalogVideoOpl");
    private final static QName _PlayReadyPlayRightExplicitAnalogTelevisionOutputRestriction_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ExplicitAnalogTelevisionOutputRestriction");
    private final static QName _PlayReadyLicenseResponseTemplateResponseCustomData_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ResponseCustomData");
    private final static QName _PlayReadyLicenseTemplateBeginDate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "BeginDate");
    private final static QName _PlayReadyLicenseTemplateGracePeriod_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "GracePeriod");
    private final static QName _PlayReadyLicenseTemplatePlayRight_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "PlayRight");
    private final static QName _PlayReadyLicenseTemplateExpirationDate_QNAME = new QName("http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", "ExpirationDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlayReadyLicenseResponseTemplate }
     * 
     */
    public PlayReadyLicenseResponseTemplate createPlayReadyLicenseResponseTemplate() {
        return new PlayReadyLicenseResponseTemplate();
    }

    /**
     * Create an instance of {@link ArrayOfPlayReadyLicenseTemplate }
     * 
     */
    public ArrayOfPlayReadyLicenseTemplate createArrayOfPlayReadyLicenseTemplate() {
        return new ArrayOfPlayReadyLicenseTemplate();
    }

    /**
     * Create an instance of {@link PlayReadyPlayRight }
     * 
     */
    public PlayReadyPlayRight createPlayReadyPlayRight() {
        return new PlayReadyPlayRight();
    }

    /**
     * Create an instance of {@link ContentEncryptionKeyFromHeader }
     * 
     */
    public ContentEncryptionKeyFromHeader createContentEncryptionKeyFromHeader() {
        return new ContentEncryptionKeyFromHeader();
    }

    /**
     * Create an instance of {@link ScmsRestriction }
     * 
     */
    public ScmsRestriction createScmsRestriction() {
        return new ScmsRestriction();
    }

    /**
     * Create an instance of {@link ContentEncryptionKeyFromKeyIdentifier }
     * 
     */
    public ContentEncryptionKeyFromKeyIdentifier createContentEncryptionKeyFromKeyIdentifier() {
        return new ContentEncryptionKeyFromKeyIdentifier();
    }

    /**
     * Create an instance of {@link AgcAndColorStripeRestriction }
     * 
     */
    public AgcAndColorStripeRestriction createAgcAndColorStripeRestriction() {
        return new AgcAndColorStripeRestriction();
    }

    /**
     * Create an instance of {@link PlayReadyContentKey }
     * 
     */
    public PlayReadyContentKey createPlayReadyContentKey() {
        return new PlayReadyContentKey();
    }

    /**
     * Create an instance of {@link PlayReadyLicenseTemplate }
     * 
     */
    public PlayReadyLicenseTemplate createPlayReadyLicenseTemplate() {
        return new PlayReadyLicenseTemplate();
    }

    /**
     * Create an instance of {@link ExplicitAnalogTelevisionRestriction }
     * 
     */
    public ExplicitAnalogTelevisionRestriction createExplicitAnalogTelevisionRestriction() {
        return new ExplicitAnalogTelevisionRestriction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExplicitAnalogTelevisionRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ExplicitAnalogTelevisionRestriction")
    public JAXBElement<ExplicitAnalogTelevisionRestriction> createExplicitAnalogTelevisionRestriction(ExplicitAnalogTelevisionRestriction value) {
        return new JAXBElement<ExplicitAnalogTelevisionRestriction>(_ExplicitAnalogTelevisionRestriction_QNAME, ExplicitAnalogTelevisionRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgcAndColorStripeRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "AgcAndColorStripeRestriction")
    public JAXBElement<AgcAndColorStripeRestriction> createAgcAndColorStripeRestriction(AgcAndColorStripeRestriction value) {
        return new JAXBElement<AgcAndColorStripeRestriction>(_AgcAndColorStripeRestriction_QNAME, AgcAndColorStripeRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyContentKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayReadyContentKey")
    public JAXBElement<PlayReadyContentKey> createPlayReadyContentKey(PlayReadyContentKey value) {
        return new JAXBElement<PlayReadyContentKey>(_PlayReadyContentKey_QNAME, PlayReadyContentKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentEncryptionKeyFromHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ContentEncryptionKeyFromHeader")
    public JAXBElement<ContentEncryptionKeyFromHeader> createContentEncryptionKeyFromHeader(ContentEncryptionKeyFromHeader value) {
        return new JAXBElement<ContentEncryptionKeyFromHeader>(_ContentEncryptionKeyFromHeader_QNAME, ContentEncryptionKeyFromHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyLicenseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayReadyLicenseType")
    public JAXBElement<PlayReadyLicenseType> createPlayReadyLicenseType(PlayReadyLicenseType value) {
        return new JAXBElement<PlayReadyLicenseType>(_PlayReadyLicenseType_QNAME, PlayReadyLicenseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyLicenseTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayReadyLicenseTemplate")
    public JAXBElement<PlayReadyLicenseTemplate> createPlayReadyLicenseTemplate(PlayReadyLicenseTemplate value) {
        return new JAXBElement<PlayReadyLicenseTemplate>(_PlayReadyLicenseTemplate_QNAME, PlayReadyLicenseTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentEncryptionKeyFromKeyIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ContentEncryptionKeyFromKeyIdentifier")
    public JAXBElement<ContentEncryptionKeyFromKeyIdentifier> createContentEncryptionKeyFromKeyIdentifier(ContentEncryptionKeyFromKeyIdentifier value) {
        return new JAXBElement<ContentEncryptionKeyFromKeyIdentifier>(_ContentEncryptionKeyFromKeyIdentifier_QNAME, ContentEncryptionKeyFromKeyIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScmsRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ScmsRestriction")
    public JAXBElement<ScmsRestriction> createScmsRestriction(ScmsRestriction value) {
        return new JAXBElement<ScmsRestriction>(_ScmsRestriction_QNAME, ScmsRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnknownOutputPassingOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "UnknownOutputPassingOption")
    public JAXBElement<UnknownOutputPassingOption> createUnknownOutputPassingOption(UnknownOutputPassingOption value) {
        return new JAXBElement<UnknownOutputPassingOption>(_UnknownOutputPassingOption_QNAME, UnknownOutputPassingOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ContentType")
    public JAXBElement<ContentType> createContentType(ContentType value) {
        return new JAXBElement<ContentType>(_ContentType_QNAME, ContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyPlayRight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayReadyPlayRight")
    public JAXBElement<PlayReadyPlayRight> createPlayReadyPlayRight(PlayReadyPlayRight value) {
        return new JAXBElement<PlayReadyPlayRight>(_PlayReadyPlayRight_QNAME, PlayReadyPlayRight.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyLicenseResponseTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayReadyLicenseResponseTemplate")
    public JAXBElement<PlayReadyLicenseResponseTemplate> createPlayReadyLicenseResponseTemplate(PlayReadyLicenseResponseTemplate value) {
        return new JAXBElement<PlayReadyLicenseResponseTemplate>(_PlayReadyLicenseResponseTemplate_QNAME, PlayReadyLicenseResponseTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPlayReadyLicenseTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ArrayOfPlayReadyLicenseTemplate")
    public JAXBElement<ArrayOfPlayReadyLicenseTemplate> createArrayOfPlayReadyLicenseTemplate(ArrayOfPlayReadyLicenseTemplate value) {
        return new JAXBElement<ArrayOfPlayReadyLicenseTemplate>(_ArrayOfPlayReadyLicenseTemplate_QNAME, ArrayOfPlayReadyLicenseTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "UncompressedDigitalVideoOpl", scope = PlayReadyPlayRight.class)
    public JAXBElement<Integer> createPlayReadyPlayRightUncompressedDigitalVideoOpl(Integer value) {
        return new JAXBElement<Integer>(_PlayReadyPlayRightUncompressedDigitalVideoOpl_QNAME, Integer.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgcAndColorStripeRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "AgcAndColorStripeRestriction", scope = PlayReadyPlayRight.class)
    public JAXBElement<AgcAndColorStripeRestriction> createPlayReadyPlayRightAgcAndColorStripeRestriction(AgcAndColorStripeRestriction value) {
        return new JAXBElement<AgcAndColorStripeRestriction>(_AgcAndColorStripeRestriction_QNAME, AgcAndColorStripeRestriction.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "UncompressedDigitalAudioOpl", scope = PlayReadyPlayRight.class)
    public JAXBElement<Integer> createPlayReadyPlayRightUncompressedDigitalAudioOpl(Integer value) {
        return new JAXBElement<Integer>(_PlayReadyPlayRightUncompressedDigitalAudioOpl_QNAME, Integer.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "CompressedDigitalAudioOpl", scope = PlayReadyPlayRight.class)
    public JAXBElement<Integer> createPlayReadyPlayRightCompressedDigitalAudioOpl(Integer value) {
        return new JAXBElement<Integer>(_PlayReadyPlayRightCompressedDigitalAudioOpl_QNAME, Integer.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "CompressedDigitalVideoOpl", scope = PlayReadyPlayRight.class)
    public JAXBElement<Integer> createPlayReadyPlayRightCompressedDigitalVideoOpl(Integer value) {
        return new JAXBElement<Integer>(_PlayReadyPlayRightCompressedDigitalVideoOpl_QNAME, Integer.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScmsRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ScmsRestriction", scope = PlayReadyPlayRight.class)
    public JAXBElement<ScmsRestriction> createPlayReadyPlayRightScmsRestriction(ScmsRestriction value) {
        return new JAXBElement<ScmsRestriction>(_ScmsRestriction_QNAME, ScmsRestriction.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "FirstPlayExpiration", scope = PlayReadyPlayRight.class)
    public JAXBElement<Duration> createPlayReadyPlayRightFirstPlayExpiration(Duration value) {
        return new JAXBElement<Duration>(_PlayReadyPlayRightFirstPlayExpiration_QNAME, Duration.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "AnalogVideoOpl", scope = PlayReadyPlayRight.class)
    public JAXBElement<Integer> createPlayReadyPlayRightAnalogVideoOpl(Integer value) {
        return new JAXBElement<Integer>(_PlayReadyPlayRightAnalogVideoOpl_QNAME, Integer.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExplicitAnalogTelevisionRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ExplicitAnalogTelevisionOutputRestriction", scope = PlayReadyPlayRight.class)
    public JAXBElement<ExplicitAnalogTelevisionRestriction> createPlayReadyPlayRightExplicitAnalogTelevisionOutputRestriction(ExplicitAnalogTelevisionRestriction value) {
        return new JAXBElement<ExplicitAnalogTelevisionRestriction>(_PlayReadyPlayRightExplicitAnalogTelevisionOutputRestriction_QNAME, ExplicitAnalogTelevisionRestriction.class, PlayReadyPlayRight.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ResponseCustomData", scope = PlayReadyLicenseResponseTemplate.class)
    public JAXBElement<String> createPlayReadyLicenseResponseTemplateResponseCustomData(String value) {
        return new JAXBElement<String>(_PlayReadyLicenseResponseTemplateResponseCustomData_QNAME, String.class, PlayReadyLicenseResponseTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "BeginDate", scope = PlayReadyLicenseTemplate.class)
    public JAXBElement<XMLGregorianCalendar> createPlayReadyLicenseTemplateBeginDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlayReadyLicenseTemplateBeginDate_QNAME, XMLGregorianCalendar.class, PlayReadyLicenseTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "GracePeriod", scope = PlayReadyLicenseTemplate.class)
    public JAXBElement<Duration> createPlayReadyLicenseTemplateGracePeriod(Duration value) {
        return new JAXBElement<Duration>(_PlayReadyLicenseTemplateGracePeriod_QNAME, Duration.class, PlayReadyLicenseTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayReadyPlayRight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "PlayRight", scope = PlayReadyLicenseTemplate.class)
    public JAXBElement<PlayReadyPlayRight> createPlayReadyLicenseTemplatePlayRight(PlayReadyPlayRight value) {
        return new JAXBElement<PlayReadyPlayRight>(_PlayReadyLicenseTemplatePlayRight_QNAME, PlayReadyPlayRight.class, PlayReadyLicenseTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", name = "ExpirationDate", scope = PlayReadyLicenseTemplate.class)
    public JAXBElement<XMLGregorianCalendar> createPlayReadyLicenseTemplateExpirationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlayReadyLicenseTemplateExpirationDate_QNAME, XMLGregorianCalendar.class, PlayReadyLicenseTemplate.class, value);
    }

}
