//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;
