//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayReadyLicenseResponseTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayReadyLicenseResponseTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LicenseTemplates" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}ArrayOfPlayReadyLicenseTemplate"/>
 *         &lt;element name="ResponseCustomData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayReadyLicenseResponseTemplate", propOrder = {
    "licenseTemplates",
    "responseCustomData"
})
public class PlayReadyLicenseResponseTemplate {

    @XmlElement(name = "LicenseTemplates", required = true, nillable = true)
    protected ArrayOfPlayReadyLicenseTemplate licenseTemplates;
    @XmlElementRef(name = "ResponseCustomData", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> responseCustomData;

    /**
     * Gets the value of the licenseTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPlayReadyLicenseTemplate }
     *     
     */
    public ArrayOfPlayReadyLicenseTemplate getLicenseTemplates() {
        return licenseTemplates;
    }

    /**
     * Sets the value of the licenseTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPlayReadyLicenseTemplate }
     *     
     */
    public void setLicenseTemplates(ArrayOfPlayReadyLicenseTemplate value) {
        this.licenseTemplates = value;
    }

    /**
     * Gets the value of the responseCustomData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getResponseCustomData() {
        return responseCustomData;
    }

    /**
     * Sets the value of the responseCustomData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setResponseCustomData(JAXBElement<String> value) {
        this.responseCustomData = value;
    }

}
