//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for PlayReadyPlayRight complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayReadyPlayRight">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgcAndColorStripeRestriction" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}AgcAndColorStripeRestriction" minOccurs="0"/>
 *         &lt;element name="AllowPassingVideoContentToUnknownOutput" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}UnknownOutputPassingOption" minOccurs="0"/>
 *         &lt;element name="AnalogVideoOpl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CompressedDigitalAudioOpl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CompressedDigitalVideoOpl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DigitalVideoOnlyContentRestriction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ExplicitAnalogTelevisionOutputRestriction" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}ExplicitAnalogTelevisionRestriction" minOccurs="0"/>
 *         &lt;element name="FirstPlayExpiration" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="ImageConstraintForAnalogComponentVideoRestriction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ImageConstraintForAnalogComputerMonitorRestriction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ScmsRestriction" type="{http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1}ScmsRestriction" minOccurs="0"/>
 *         &lt;element name="UncompressedDigitalAudioOpl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="UncompressedDigitalVideoOpl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayReadyPlayRight", propOrder = {
    "agcAndColorStripeRestriction",
    "allowPassingVideoContentToUnknownOutput",
    "analogVideoOpl",
    "compressedDigitalAudioOpl",
    "compressedDigitalVideoOpl",
    "digitalVideoOnlyContentRestriction",
    "explicitAnalogTelevisionOutputRestriction",
    "firstPlayExpiration",
    "imageConstraintForAnalogComponentVideoRestriction",
    "imageConstraintForAnalogComputerMonitorRestriction",
    "scmsRestriction",
    "uncompressedDigitalAudioOpl",
    "uncompressedDigitalVideoOpl"
})
public class PlayReadyPlayRight {

    @XmlElementRef(name = "AgcAndColorStripeRestriction", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<AgcAndColorStripeRestriction> agcAndColorStripeRestriction;
    @XmlElement(name = "AllowPassingVideoContentToUnknownOutput")
    @XmlSchemaType(name = "string")
    protected UnknownOutputPassingOption allowPassingVideoContentToUnknownOutput;
    @XmlElementRef(name = "AnalogVideoOpl", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> analogVideoOpl;
    @XmlElementRef(name = "CompressedDigitalAudioOpl", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> compressedDigitalAudioOpl;
    @XmlElementRef(name = "CompressedDigitalVideoOpl", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> compressedDigitalVideoOpl;
    @XmlElement(name = "DigitalVideoOnlyContentRestriction")
    protected Boolean digitalVideoOnlyContentRestriction;
    @XmlElementRef(name = "ExplicitAnalogTelevisionOutputRestriction", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<ExplicitAnalogTelevisionRestriction> explicitAnalogTelevisionOutputRestriction;
    @XmlElementRef(name = "FirstPlayExpiration", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Duration> firstPlayExpiration;
    @XmlElement(name = "ImageConstraintForAnalogComponentVideoRestriction")
    protected Boolean imageConstraintForAnalogComponentVideoRestriction;
    @XmlElement(name = "ImageConstraintForAnalogComputerMonitorRestriction")
    protected Boolean imageConstraintForAnalogComputerMonitorRestriction;
    @XmlElementRef(name = "ScmsRestriction", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<ScmsRestriction> scmsRestriction;
    @XmlElementRef(name = "UncompressedDigitalAudioOpl", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> uncompressedDigitalAudioOpl;
    @XmlElementRef(name = "UncompressedDigitalVideoOpl", namespace = "http://schemas.microsoft.com/Azure/MediaServices/KeyDelivery/PlayReadyTemplate/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> uncompressedDigitalVideoOpl;

    /**
     * Gets the value of the agcAndColorStripeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AgcAndColorStripeRestriction }{@code >}
     *     
     */
    public JAXBElement<AgcAndColorStripeRestriction> getAgcAndColorStripeRestriction() {
        return agcAndColorStripeRestriction;
    }

    /**
     * Sets the value of the agcAndColorStripeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AgcAndColorStripeRestriction }{@code >}
     *     
     */
    public void setAgcAndColorStripeRestriction(JAXBElement<AgcAndColorStripeRestriction> value) {
        this.agcAndColorStripeRestriction = value;
    }

    /**
     * Gets the value of the allowPassingVideoContentToUnknownOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UnknownOutputPassingOption }
     *     
     */
    public UnknownOutputPassingOption getAllowPassingVideoContentToUnknownOutput() {
        return allowPassingVideoContentToUnknownOutput;
    }

    /**
     * Sets the value of the allowPassingVideoContentToUnknownOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnknownOutputPassingOption }
     *     
     */
    public void setAllowPassingVideoContentToUnknownOutput(UnknownOutputPassingOption value) {
        this.allowPassingVideoContentToUnknownOutput = value;
    }

    /**
     * Gets the value of the analogVideoOpl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAnalogVideoOpl() {
        return analogVideoOpl;
    }

    /**
     * Sets the value of the analogVideoOpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAnalogVideoOpl(JAXBElement<Integer> value) {
        this.analogVideoOpl = value;
    }

    /**
     * Gets the value of the compressedDigitalAudioOpl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getCompressedDigitalAudioOpl() {
        return compressedDigitalAudioOpl;
    }

    /**
     * Sets the value of the compressedDigitalAudioOpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setCompressedDigitalAudioOpl(JAXBElement<Integer> value) {
        this.compressedDigitalAudioOpl = value;
    }

    /**
     * Gets the value of the compressedDigitalVideoOpl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getCompressedDigitalVideoOpl() {
        return compressedDigitalVideoOpl;
    }

    /**
     * Sets the value of the compressedDigitalVideoOpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setCompressedDigitalVideoOpl(JAXBElement<Integer> value) {
        this.compressedDigitalVideoOpl = value;
    }

    /**
     * Gets the value of the digitalVideoOnlyContentRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDigitalVideoOnlyContentRestriction() {
        return digitalVideoOnlyContentRestriction;
    }

    /**
     * Sets the value of the digitalVideoOnlyContentRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDigitalVideoOnlyContentRestriction(Boolean value) {
        this.digitalVideoOnlyContentRestriction = value;
    }

    /**
     * Gets the value of the explicitAnalogTelevisionOutputRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExplicitAnalogTelevisionRestriction }{@code >}
     *     
     */
    public JAXBElement<ExplicitAnalogTelevisionRestriction> getExplicitAnalogTelevisionOutputRestriction() {
        return explicitAnalogTelevisionOutputRestriction;
    }

    /**
     * Sets the value of the explicitAnalogTelevisionOutputRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExplicitAnalogTelevisionRestriction }{@code >}
     *     
     */
    public void setExplicitAnalogTelevisionOutputRestriction(JAXBElement<ExplicitAnalogTelevisionRestriction> value) {
        this.explicitAnalogTelevisionOutputRestriction = value;
    }

    /**
     * Gets the value of the firstPlayExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public JAXBElement<Duration> getFirstPlayExpiration() {
        return firstPlayExpiration;
    }

    /**
     * Sets the value of the firstPlayExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public void setFirstPlayExpiration(JAXBElement<Duration> value) {
        this.firstPlayExpiration = value;
    }

    /**
     * Gets the value of the imageConstraintForAnalogComponentVideoRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImageConstraintForAnalogComponentVideoRestriction() {
        return imageConstraintForAnalogComponentVideoRestriction;
    }

    /**
     * Sets the value of the imageConstraintForAnalogComponentVideoRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImageConstraintForAnalogComponentVideoRestriction(Boolean value) {
        this.imageConstraintForAnalogComponentVideoRestriction = value;
    }

    /**
     * Gets the value of the imageConstraintForAnalogComputerMonitorRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImageConstraintForAnalogComputerMonitorRestriction() {
        return imageConstraintForAnalogComputerMonitorRestriction;
    }

    /**
     * Sets the value of the imageConstraintForAnalogComputerMonitorRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImageConstraintForAnalogComputerMonitorRestriction(Boolean value) {
        this.imageConstraintForAnalogComputerMonitorRestriction = value;
    }

    /**
     * Gets the value of the scmsRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ScmsRestriction }{@code >}
     *     
     */
    public JAXBElement<ScmsRestriction> getScmsRestriction() {
        return scmsRestriction;
    }

    /**
     * Sets the value of the scmsRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ScmsRestriction }{@code >}
     *     
     */
    public void setScmsRestriction(JAXBElement<ScmsRestriction> value) {
        this.scmsRestriction = value;
    }

    /**
     * Gets the value of the uncompressedDigitalAudioOpl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getUncompressedDigitalAudioOpl() {
        return uncompressedDigitalAudioOpl;
    }

    /**
     * Sets the value of the uncompressedDigitalAudioOpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setUncompressedDigitalAudioOpl(JAXBElement<Integer> value) {
        this.uncompressedDigitalAudioOpl = value;
    }

    /**
     * Gets the value of the uncompressedDigitalVideoOpl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getUncompressedDigitalVideoOpl() {
        return uncompressedDigitalVideoOpl;
    }

    /**
     * Sets the value of the uncompressedDigitalVideoOpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setUncompressedDigitalVideoOpl(JAXBElement<Integer> value) {
        this.uncompressedDigitalVideoOpl = value;
    }

}
