//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 01:26:02 PM CEST 
//


package io.as.ams.contentkeyauthorizationpolicyoptions.playreadylicenseresponsetemplate;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayReadyLicenseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlayReadyLicenseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Nonpersistent"/>
 *     &lt;enumeration value="Persistent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlayReadyLicenseType")
@XmlEnum
public enum PlayReadyLicenseType {

    @XmlEnumValue("Nonpersistent")
    NONPERSISTENT("Nonpersistent"),
    @XmlEnumValue("Persistent")
    PERSISTENT("Persistent");
    private final String value;

    PlayReadyLicenseType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlayReadyLicenseType fromValue(String v) {
        for (PlayReadyLicenseType c: PlayReadyLicenseType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
